### ISSUE TITLE
Secondary Subs Not Working

### ISSUE THREAD

**Issue by nickstack** [gmertes/NflxMultiSubs#33] opened 2022-12-07 04:49 UTC
Secondary subtitles have stopped working using Chrome.

**Comment by dongsibo** [comment] 2022-12-07 05:07
Seems to be due to a recent Netflix update. The issue is fixed for me on Firefox with NflxMultiSubs [v2.3.2](https://github.com/gmertes/NflxMultiSubs/compare/v2.3.1...v2.3.2), but this version hasn't been pushed to Chrome Web Store or Firefox Add-ons yet.

**Comment by gmertes** [comment] 2022-12-07 21:39
> I found that on some of my devices the change made by Netflix isn't live yet (and v2.3.1 still works 🤔)

I re-added the old code as a fallback so that it now works with both the old and new version of the Netflix player.

This issue is now completely resolved in v2.3.3, which is live on Firefox addons. It's pending approval on the Chrome store at the time of writing, but it was already fixed in the live version there.

**Closed by gmertes** 2022-12-07 21:39 UTC
Labels: fixed

**Comment by WingCH** [comment] 2022-12-08 15:44
Thanks for notice!
Just updated to new version and upload to apple, waiting for apple review now.

**Comment by WingCH** [comment] 2022-12-09 14:35
The new version has been released on the Apple Store, thanks
