### ISSUE TITLE
Secondary subtitles are not shown after moved to next episode

### ISSUE THREAD

**Issue by sh-cho** [gmertes/NflxMultiSubs#15] opened 2021-11-02 15:21 UTC
![image](https://user-images.githubusercontent.com/11611397/139875634-8673e7ad-58bf-48ac-8571-f5674b5ad390.png)

When I moved to next episode, secondary subtitles are checked but not shown in screen.

If I check "Off" and select the secondary subtitles again, it works fine.

("La Casa de Papel", S01 E05 -> E06)

**Comment by gmertes** [comment] 2021-11-03 12:18
Hmm I can't reproduce this bug, for me it activates the subtitle correctly when going to next ep. Gonna need some more info:

1. Which version of the plugin, which browser, and installed from where?
2. Did you previously install the plugin manually using the zip file?
3. Does it happen all the time when going to the next episode, or only sometimes? 
4. Could you please reproduce the bug in a new tab and then paste the output of the console log here? Make sure that logging is set to show info, warning and error.

**Comment by sh-cho** [comment] 2021-11-03 13:46
1. plugin version: `2.2.5` / chrome browser on mac: `Version 95.0.4638.69 (Official Build) (arm64)`
2. I had installed [this](https://chrome.google.com/webstore/detail/nflxmultisubs-netflix-mul/pjhnilfooknlkdonmjnleaomamfehkli) first, and found it's not working.
  So I removed it and installed this extension through [Chrome Web Store](https://chrome.google.com/webstore/detail/nflxmultisubs-2021-netfli/jepfhfjlkgobooomdgpcjikalfpcldmm)
3. It happens all the time
4.
![image](https://user-images.githubusercontent.com/11611397/140067344-ac7455e7-9276-45ea-9424-049985012f16.png)

**Comment by gmertes** [comment] 2021-11-03 18:34
Found and fixed the bug. Netflix changed the manifest format and removed the field we used to detect the default audio language. This broke the subtitle auto-activation based on audio language. So it wasn't just broken when going to the next episode, but broken completely. I couldn't reproduce it earlier because I was using the 'last used' language mode 🙃

Thanks again for your report because this was a major bug. The fix will be included in the next release (v2.2.6). You can expect the update in the next few days once it's approved by the Chrome store. In the meantime I suggest to keep using the 'last used' language mode. I'll close this issue once the update is rolled out.

**Comment by gmertes** [comment] 2021-11-06 12:31
v2.2.6 with the fix is now live on both stores 🎉

**Closed by gmertes** 2021-11-06 12:31 UTC
Labels: bug
