### ISSUE TITLE
Subtitles are one on top of the other

### ISSUE THREAD

**Issue by filippogiad** [gmertes/NflxMultiSubs#44] opened 2023-06-25 20:03 UTC
<img width="1175" alt="Screenshot 2023-06-25 alle 22 01 45" src="https://github.com/gmertes/NflxMultiSubs/assets/17814576/e266f6df-0e42-4f4b-b9b6-0e46a7cec93b">

This seems to happen only with the "The lighthouse" movie

**Comment by gmertes** [comment] 2023-06-26 23:29
Hi! Thanks for the report. Unfortunately I don't have the lighthouse in my region, and I can't immediately reproduce the problem on another title :( 

1) Do both the primary and secondary subtitles move down when the progress bar disappears?
2) Could you show me the console log output? 
3) Do you have any other Netflix related addons installed?

**Comment by filippogiad** [comment] 2023-06-27 16:45
Ciao! Happy to help!


> Hi! Thanks for the report. Unfortunately I don't have the lighthouse in my region, and I can't immediately reproduce the problem on another title :(
> 
>     1. Do both the primary and secondary subtitles move down when the progress bar disappears? Yes, they move down a bit but they remain one up the other
> 
>     2. Could you show me the console log output? Could you explain me how, please :) i just receive the messages you see below.
> 
>     3. Do you have any other Netflix related addons installed? no other addons realted to Netflix.


18:39:51.079 Alcuni cookie utilizzano l’attributo “SameSite“ consigliato in modo non corretto 5
18:40:05.670 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 6 background.js:1
    sendMessage moz-extension://46c9e57a-791e-419d-9d18-a3d053d55903/background.js:1
18:40:52.558 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 4 background.js:1
    sendMessage moz-extension://46c9e57a-791e-419d-9d18-a3d053d55903/background.js:1
18:41:05.532 NotFoundError: No such JSWindowActor 'DevToolsFrame' 22
18:41:10.772 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
    sendMessage moz-extension://46c9e57a-791e-419d-9d18-a3d053d55903/background.js:1
18:41:45.376 Error: Unknown file format
    p moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js:1
    setup moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js:1
    parse moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js:1
    $ moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js:1
background.js:1:9159
    fetchExif moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js:1
18:41:45.926 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
18:42:05.191 Questa pagina si trova in modalità Quirks. Questo potrebbe avere effetto sul layout della pagina. Per la modalità standard utilizzare “<!DOCTYPE html>”. background.js
18:42:05.247 Could not find any MenuItem with id: root background.js:1:157846
18:42:05.258 È stato fornito a “view-source:moz-extension://5a9b8482-9d9e-42d8-8acb-a97375ade58a/background.js” un cookie partizionato o accesso alle risorse di archiviazione in quanto è caricato in un contesto di terze parti e il partizionamento di stato dinamico è attivo.
18:42:05.288 Could not find any MenuItem with id: autofill background.js:1:157846
18:42:05.289 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 5 background.js:1
18:43:21.370 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1

**Comment by gmertes** [comment] 2023-07-23 18:29
Hey sorry for the long wait. Still wasn't able to reproduce this on any other movie/show :( Since it only happens on this 1 movie I'm going to close this for now - but let me know if it happens on any other shows.

**Closed by gmertes** 2023-07-23 18:29 UTC
